### ISSUE TITLE
添加icon序列化

### ISSUE THREAD

**Issue by Iroha1024** [iconfont-cli/flutter-iconfont-cli#12]
遇到需要存储IconNames到本地的情况

改了一下模板
大概就是这样https://github.com/Iroha1024/flutter-iconfont-cli/commit/e880c4849d5a209f4c3121f13eb481d4993cbff5

String serialize():  IconNames.iconName   -->  'iconName'
额外提供getIconNames、供提前获取IconNames

话说readme没有引导说明，不太懂怎么进行本地调试的。还得手动tsc build，挪动文件进行测试😳

**Comment by fwh1990** [comment]
`sh ./scripts/update-snapshot.sh`生成新的快照即可

提个PR

**Comment by Iroha1024** [comment]
提交了
