### ISSUE TITLE
生成文件的命名格式不对

### ISSUE THREAD

**Issue by i-show** [iconfont-cli/flutter-iconfont-cli#4]
Dart的文件命名格式为 小写+下划线的形式。例如：aa_bb.dart , icon_font.dart

**Comment by fwh1990** [comment]
会报错吗？还是说下划线是约定的写法？

**Comment by i-show** [comment]
> 会报错吗？还是说下划线是约定的写法？

不会报错，是不符合Dart的约定写法。 官方的约定为：https://dart.dev/guides/language/effective-dart/style

![image](https://user-images.githubusercontent.com/5258055/92708788-f9301080-f388-11ea-8920-62b4d8772dcf.png)

**Comment by fwh1990** [comment]
好的，我改一下

**Comment by fwh1990** [comment]
升级到1.0解决文件名问题
