### ISSUE TITLE
1 不支持数字开头，2 不知为何数字会加入 _ 分割

### ISSUE THREAD

**Issue by seateam** [iconfont-cli/flutter-iconfont-cli#7]
case '500_px':
        iconName = IconNames.500_px;
        break;

case '360':
        iconName = IconNames.360;
        break;

case 'w_3_school':
        iconName = IconNames.w_3_school;
        break;

**Comment by seateam** [comment]
提议字符串是没问题的， 定义对象的时候，可以用 _ 放在前面

**Comment by seateam** [comment]
作者人呢

**Comment by fwh1990** [comment]
使用数字会有语法上的报错吗？

**Comment by seateam** [comment]
```js
case '360':
        iconName = IconNames._360;
        break;
case 'w3school':
        iconName = IconNames.w3school;
        break;
case 'v2ex':
        iconName = IconNames.v2ex;
        break;
case '500px':
        iconName = IconNames._500px;
        break;
```
我目前是这样处理的， 数字开头加 下划线， 字符串形式不受影响

**Comment by seateam** [comment]
你可以用这个文件试下 //at.alicdn.com/t/font_2137730_4bwxxhmwm4a.js

**Comment by fwh1990** [comment]
发布了1.0.1

**Comment by seateam** [comment]
字符串匹配，还是有点问题
case '500px':
希望和 iconfont 保持一致
case '_500_px':

**Comment by fwh1990** [comment]
用的是 lodash.snakeCase ，没有比较好的替代方案，

**Comment by fwh1990** [comment]
用的是 lodash.snakeCase ，没有比较好的替代方案，

**Comment by seateam** [comment]
good
