### ISSUE TITLE
能否支持dart 2.12.0的 null safety 特性？

### ISSUE THREAD

**Issue by xiaoshuimao** [iconfont-cli/flutter-iconfont-cli#9]
![image](https://user-images.githubusercontent.com/6658087/109949252-1b8e5f80-7d16-11eb-94e0-832cbe02a6f5.png)

**Comment by fwh1990** [comment]
也许应该加一个配置参数？因为默认sdk是 ">=2.7.0 <3.0.0" ，这种情况下反而不能用null-safety特性。

**Comment by fwh1990** [comment]
https://github.com/iconfont-cli/flutter-iconfont-cli/blob/master/snapshots/null_safety.dart
这个文件复制到项目里看下会不会报错

**Comment by xiaoshuimao** [comment]
@fwh1990 这个文件没问题

**Comment by fwh1990** [comment]
1.1.0。https://github.com/iconfont-cli/flutter-iconfont-cli#null_safety
